### ISSUE TITLE
embed kustomize binary

### ISSUE THREAD

**Issue by hansanghoon** [bitnami/bitnami-docker-kubectl#11]
**Description**

Actually not an issue, but suggestion/request. 
kubectl has embedded kustomize, but its version is too low as `2.0.3`. Current kustomize version is `3.5.x` and gap is way too wide. Does it make sense to embed kustomize cli into bitnami/kubectl container?

**Steps to reproduce the issue:**

1. `kustomize build overlay/someoverlay | kubectl apply -f -`

**Describe the results you received:** no kustomize cli

**Describe the results you expected:** kustomize cli is available inside bitnami/docker container.

**Comment by andresbono** [comment]
Hi @hansanghoon, thanks for opening this PR.

For the `kubectl` container we just package the upstream `kubectl` binary without doing any modifications. We would like to keep this container as simple and transparent as possible.

Would it make sense for you to create your own custom image based on this one? In your new Dockerfile, you can download the `kustomize` binary from the version that you require.

Let us know your thoughts on this approach!
