### ISSUE TITLE
install_packages: List directory /var/lib/apt/lists/partial is missing

### ISSUE THREAD

**Issue by JeroenVanOort** [bitnami/bitnami-docker-kubectl#17]
**Description**
I wanted to install a package using the install_packages script. However, this error is thrown:

`E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)`

**Steps to reproduce the issue:**

1. Get shell access to `bitnami/kubectl`.
2. Run `install_packages gettext_base`

**Describe the results you received:**
`E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)`

**Describe the results you expected:**

A successful install

**Additional information you deem important (e.g. issue happens only occasionally):**

I happen to be running this in Gitlab CI, but I don't think it is very important.

**Comment by rafariossaa** [comment]
Hi,
  As the container is non-root, you can see in the Dockerfile that the user used is 1001, you can not run this command directly.
  You will need to get access to the container using root, then you will be able to use `install_packages`.
  To get access as root, you can add ` -u root` to your `docker exec`  or `docker run` commands.

**Comment by JeroenVanOort** [comment]
Thank you for your reply. I've created my own image, because Gitlab doesn't allow passing the user to Docker.

**Comment by rafariossaa** [comment]
Hi,  
  I am happy you where able to find a solution.
