### ISSUE TITLE
image not running in Kubernetes

### ISSUE THREAD

**Issue by abhiramani-iptiq** [bitnami/bitnami-docker-kubectl#18]
**Description**
Unable to run image in kubernetes

**Steps to reproduce the issue:**

 kubectl run -i -t --image=bitnami/kubectl:latest mytest

**Describe the results you received:**

its goes in crashloop and after few restart it terminates

When runnign this command 

image should running 

Azure kubernetes 1.18

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
The [`ENTRYPOINT`](https://github.com/bitnami/bitnami-docker-kubectl/blob/06a4326789287f75aff2875a3421422e0dd2cb03/1.18/debian-10/Dockerfile#L25) and [`CMD`](https://github.com/bitnami/bitnami-docker-kubectl/blob/06a4326789287f75aff2875a3421422e0dd2cb03/1.18/debian-10/Dockerfile#L26) of this image are going to execute `kubectl --help` that is an ephemeral command so the execution of this container is going to die once the command is executed. You need to pass your desired `kubectl` command as an argument, but it is going to die in the same way once executed the command, for example using `docker run` and the `version` command from the `kubectl` CLI:
```console
$ docker run --rm --name kubectl bitnami/kubectl:latest version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-15T01:52:24Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
