### ISSUE TITLE
Consider adding gettext-base package

### ISSUE THREAD

**Issue by santachago** [bitnami/bitnami-docker-kubectl#20]
I think it would be useful for this image to have `envsubst` this way the deployment file can be used as template and updated from ENV variables.
running:
`- envsubst < deployment-template.yml | kubectl apply -f -`

**Comment by juan131** [comment]
Hi @santachago 

Thanks so much for your suggestion! It thinks it's a good idea to consider.

IMHO, we should keep this container as slim and simple as possible. We can always delegate the rendering capabilities to a third container/system, so pure YAML/JSON are injected in the **kubectl** container to be deployed. Sth like this:

```
 ┌────────────┐    ┌────────────┐      ┌────────────┐
 │  Templates │ ──▶│ Rendering  | ────▶│ Kubectl    |
 |            │    | system     | YAML | container  |
 └────────────┘    └────────────┘      └────────────┘
```

**Comment by santachago** [comment]
Thanks completely understand your explanation. Since i am using this on a CI/CD pipeline will build the yml at the same time i build the image..
many thanks!
