### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [bitnami/bitnami-docker-kubectl#22]
Hi Team,

I am trying to use **bitnami/kubectl** on ARM64 architecture but it seems the arm64 tag is not available in Docker Hub.

I tried to build the image using the command **docker build -t <image_name>** . It looks that it is using **bitnami/minideb** as the base image which is not available for arm64. I have used the changes mentioned in the [PR](
https://github.com/bitnami/minideb/pull/90) and built the **bitnami/minideb** image for arm64. 

Further, I have got the error while downloading kubectl binary from [here](https://downloads.bitnami.com/files/stacksmith/kubectl-1.20.2-0-linux-amd64-debian-10.tar.gz) as arm64 binary is not available in that.

I have downloaded the kubectl binary for arm64 from [here](https://storage.googleapis.com/kubernetes-release/release/v1.19.2/bin/linux/arm64/kubectl) and replaced it in the image. After that, the image was built successfully.

It will be very helpful if you could please release the kubectl binary and kubectl image for arm64.

If required, I am happy to contribute.

**Comment by migruiz4** [comment]
Hi @odidev,

Releasing the Bitnami catalog compatible with arm64 is in our roadmap. At the moment I can not give you an estimation date, but it will be available at some point in the future.

Thank you for your contribution offer but it requires internal development to release the arm64 binaries included in the images.

If you wish, we can keep this ticket open and I will let you know when the arm64 image is released.

**Comment by odidev** [comment]
Thanks for the info.

**Comment by lunderhage** [comment]
Are we in the future now? ;-)

**Comment by migruiz4** [comment]
Hi @lunderhage,

We have created this issue https://github.com/bitnami/charts/issues/7305 which is pinned in the Bitnami Helm Charts repository, there we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
