### ISSUE TITLE
Not able to connect to server

### ISSUE THREAD

**Issue by allinonedashboard** [bitnami/bitnami-docker-kubectl#26]
**Description**

Not able to see the server version on my machine.

**Steps to reproduce the issue:**
1. if i try with kubectl version--short
![image](https://user-images.githubusercontent.com/50626781/122204901-8f084700-ce97-11eb-9fa8-1975e3c0a834.png)
2. if i am trying with the docker command.(docker run --rm -v /c/Users/tchakka/.kube/config:/root/.kube/config --name kubectl bitnami/kubectl:latest version)
![image](https://user-images.githubusercontent.com/50626781/122205016-ae06d900-ce97-11eb-9c35-b3f845b86128.png)

**Describe the results you received:**
The connection to the server localhost:8080 was refused - did you specify the right host or port?
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

**Not showing server version**

**Additional information you deem important (e.g. issue happens only occasionally):**
It need to show the server and client version

**Version**

- Output of `docker version`:

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 47
  Running: 32
  Paused: 0
  Stopped: 15
 Images: 21
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.38GiB
 Name: docker-desktop
 ID: RYCW:VFJC:YGIK:M3BH:PAFT:RVJA:VJ4J:BSON:D54U:BN4O:ICUK:U7TM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @allinonedashboard ,
Probably what is happening is that mounting the kubeconfig pointing to `localhost` is catching the `localhost` address inside the `kubectl` container instead of your computer.
You would need to specify a non `localhost` address in the kubeconfig.

**Comment by allinonedashboard** [comment]
HI @miguelaeh 
I dont think its a issue. When i try from my local machine i am able to access. But when i try from docker image. it is causing an issue. Please correct me if I am wrong.
![image](https://user-images.githubusercontent.com/50626781/122436216-8d6e7a00-cf90-11eb-8b4e-b3ac103298ad.png)

**Comment by allinonedashboard** [comment]
Working: Kubectl get ds 
Not Working: docker run -v /c/Users/tchakka/.kube/config:/root/.kube/config  bitnami/kubectl:1.16.3 get ds

**Comment by miguelaeh** [comment]
Hi @allinonedashboard ,
As I said, running the Kubectl container a localhost request will be resolved inside the container (think on it like if it were a different machine). In your local computer localhost can be resolved to the property cluster, but inside the container localhost refers to the container itself not to your computer.

**Comment by allinonedashboard** [comment]
@miguelaeh Do i need to expose the port to make it working. Inside the docker image or through docker run command

**Comment by miguelaeh** [comment]
Hi @allinonedashboard ,
You can try using the `-p` argument for the `docker run` command.

**Comment by allinonedashboard** [comment]
@miguelaeh, Thanks for the inputs. Still its the same issue
![image](https://user-images.githubusercontent.com/50626781/123069156-70133300-d40a-11eb-998d-37e550dedb32.png)

**Comment by miguelaeh** [comment]
Hi @allinonedashboard ,
My fault, you cannot do that since the port forward works from the container to the machine.
I guess you would need to use any other IP reachable from the container

**Comment by allinonedashboard** [comment]
Hi @miguelaeh 
Thanks for the clarification. I tried to change the port of the host and container. But still its the same. I can't see the server version.
**docker -p <host-port>:<container-port> image**
![image](https://user-images.githubusercontent.com/50626781/123227331-63571380-d4cc-11eb-822c-0ea764dfb2d3.png)

**Comment by miguelaeh** [comment]
Hi @allinonedashboard ,
I wanted to say that you will need to connect to a cluster that is on a reachable IP that is not `localhost`. An IP that can be accessed from any machine since the docker network is different than your local one.
I would recommend you to read this https://docs.docker.com/network/
