### ISSUE TITLE
Running multiple kubectl commands in docker

### ISSUE THREAD

**Issue by User0394934** [bitnami/bitnami-docker-kubectl#27]
I am having problem on running multiple kubectl commands on docker container. I have 2 questions :

One is for loading using this "docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest"

second one for scaling using "kubectl scale [--resource-version=version] [--current-replicas=count] --replicas=COUNT (-f FILENAME | TYPE NAME)"

Now if I want to run these two kubectl in one command line how it can be done ?  is it like this 

1.  "docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest   scale [--resource-version=version] [--current-replicas=count] --replicas=COUNT (-f FILENAME | TYPE NAME)"

or if just want to run the scale command inside the docker container after the 1st kubectl command then should i use 2nd kubectl command like this below

2.  "docker run --rm kubectl scale [--resource-version=version] [--current-replicas=count] --replicas=COUNT (-f FILENAME | TYPE NAME)"

I am using azure devops yaml file and the sample script is like this

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: securefilevariablename
  inputs:
    secureFile: 'someconfigfile.yml'
- task: CmdLine@2

  inputs:
    script: 'docker run --rm --name kubectl -v $(securefilevariablename.secureFilePath):/.kube/config bitnami/kubectl:latest kubectl scale -n namespacename --replicas=0 deployment name'

task: Kubernetes@1
inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Samplesubname'
    azureResourceGroup: 'resource group name'
    kubernetesCluster: 'clustername'
    namespace: 'namespace'
    useConfigurationFile: true
    configuration: '$(securefilevariablename.secureFilePath)'
    secretType: 'secrettypename'
    containerRegistryType: 'Registrytype'
    checkLatest: true

**Comment by migruiz4** [comment]
Hi @User0394934,

Your first approach would be the correct one. The command should look like this:

```
docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest scale [--resource-version=version] [--current-replicas=count] --replicas=COUNT (-f FILENAME | TYPE NAME)"
```

Each option is meant for:
- `docker run`.
- `--rm`: Remove the container after the command has been executed.
- `--name kubectl`: Set the container name as 'kubectl'.
- `-v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest`: Mounts Kubernetes configuration as a volume.
- `bitnami/kubectl:latest`: Container image.

After the container image, you can provide any arguments accepted by the `kubectl` command.

---

Please be careful to not provide `kubectl` again as in your Azure DevOps yaml, because that will cause the command to fail.

Incorrect:
```
$ docker run --name kubectl --rm -v ~/.kube/config:/.kube/config bitnami/kubectl:latest kubectl config view
Error: unknown command "kubectl" for "kubectl"
Run 'kubectl --help' for usage.
```

Correct:
```
docker run --name kubectl --rm -v ~/.kube/config:/.kube/config bitnami/kubectl:latest config view
```

**Comment by User0394934** [comment]
Thanks for clarifying. This is the perfect answer.

**Comment by User0394934** [comment]
HI migruiz4 

If i want to run multiple kubectl commands how should I use "or" commands between them or may be another way. for example
these 4 commands

docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest kubectl scale -n namespacename   –replicas=0 deployment aaa

docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest kubectl scale -n namespacename   –replicas=0 deployment   bbb

docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest kubectl scale -n namespacename   –replicas=0 deployment   ccc

docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest kubectl scale  -n namespacename   –replicas=0 deployment  ddd

 Thank you

**Comment by migruiz4** [comment]
Hi @User0394934,

If you want to execute multiple commands, running docker run several times should work.
```bash
#Creates a container, runs the command `kubectl scale deployment aaa`, removes the container 
docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest scale -n namespacename –replicas=0 deployment aaa

#Creates a container, runs the command `kubectl scale deployment bbb`, removes the container 
docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest scale -n namespacename –replicas=0 deployment bbb

#Creates a container, runs the command `kubectl scale deployment ccc`, removes the container 
docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest scale -n namespacename –replicas=0 deployment ccc
```

This should work if your commands don't have dependencies between them.

---
#### Alternative 2

If you'd like to use more complex logic, you could also create a script and use it as the container entrypoint.

##### my_entrypoint.sh
```bash
#!/bin/bash

## Your bash logic here
kubectl scale -n namespacename –replicas=0 deployment aaa
kubectl scale -n namespacename –replicas=0 deployment bbb
...

## Run additional commands
echo ""
exec "$@"

```

 ##### CLI
```bash
# Change my_entrypoint.sh ownership (First time only)
sudo chmod u+x my_entrypoint.sh
sudo chown 1001:0 my_entrypoint.sh
# Run the container
docker run --rm --name kubectl -v /path/to/my_entrypoint.sh:/entrypoint.sh -v /path/to/your/kube/config:/.kube/config --entrypoint="/entrypoint.sh" bitnami/kubectl:latest
```

**Comment by User0394934** [comment]
Thanks @migruiz4 but I was looking for something in which running docker is common i.e only 1 time docker should run and then following all commands are of Kubectl,

for example something like this 

docker run --rm --name kubectl -v /path/to/your/kube/config:/.kube/config bitnami/kubectl:latest kubectl scale -n namespacename –replicas=0 deployment aaa  && namespacename –replicas=0 deployment bbb && namespacename –replicas=0 deployment ccc && namespacename –replicas=0 deployment ddd 

and so on.

By the way thanks for other alternative too. It will be useful at later point of time.

**Comment by migruiz4** [comment]
Sorry for the misunderstanding!

Yes, another alternative to run multiple commands as you described, would be:
```
docker run --rm --entrypoint="" bitnami/kubectl:latest bash -c "kubectl scale -n namespacename –replicas=0 deployment aaa; kubectl scale -n namespacename –replicas=0 deployment bbb"
```

- `--entrypoint=""` removes the Container default entrypoint:
  https://github.com/bitnami/bitnami-docker-kubectl/blob/eb4db2d2acabfadfbf0933f75d1c5ecc1fba1a82/1.21/debian-10/Dockerfile#L23
- The command executed by the container would be `bash -c "<your_bash_commands>"`. The command will be executed inside the container, and you could use any valid Bash syntax.

I think this may fit better what you were looking for.

If you need further help please let me know.

**Comment by User0394934** [comment]
Thank you, this is what I was looking for.

**Comment by migruiz4** [comment]
Great! I'm glad you found my answer helpful.
