### ISSUE TITLE
Release image based on debian 11

### ISSUE THREAD

**Issue by tareqhs** [bitnami/bitnami-docker-kubectl#29]
**Description**

Hi,

Debian 11 Bullseye has been released a month ago and some project already already adopting it.
In the context of bitnami kubectl image debian 11 is very relevant beacuse it upgrades jq from 1.5 to 1.6, and jq is a very important tools imho.

**Comment by juan131** [comment]
Hi @tareqhs 

We already added support for Debian 11 in the base image that we use to build our container catalog, see:

- https://github.com/bitnami/minideb/pull/110

At some point we'll start replacing buster with bullseye as the base image to build the catalog. However, there's no immediate plan to work on that.

In the meantime, you can build your own Debian 11 based image editing our [Dockerfile|https://github.com/bitnami/bitnami-docker-kubectl/blob/master/1.22/debian-10/Dockerfile#L1] so you apply the changes below:

```diff
-FROM docker.io/bitnami/minideb:buster
+FROM docker.io/bitnami/minideb:bullseye
```

**Comment by philjb** [comment]
I wanted to voice support for this work to provide bullseye based images. I understand that you are aware of it with no timeline (reasonable) and you have provided a work-around. Thanks!

**Comment by carrodher** [comment]
Thanks for the reminder. Yes, we are aware of that and it is part of our roadmap. There is some work/effort already in place for this topic but migrating the whole catalogue of container images and Helm charts to a new major version of their base image is not trivial, that's why we can't promise any ETA
