### ISSUE TITLE
failed to write cache due to mkdir /.kube: permission denied

### ISSUE THREAD

**Issue by mac-chaffee** [bitnami/bitnami-docker-kubectl#30]
**Description**
Since this container runs as a non-root user, it cannot create the /.kube directory, which is needed for kubectl to cache files.

This results in so many requests being sent to the apiserver that kubectl throttles itself:
```
I1130 00:26:16.420352      20 request.go:665] Waited for 1.191715678s due to client-side throttling, not priority and fairness, request: GET:https://10.20.0.1:443/apis/scheduling.k8s.io/v1?timeout=32s
```

**Steps to reproduce the issue:**

1. Create a cluster with many extra CRDs. I have 91. (unsure of the specific threshold to trigger throttling, or if this step is even required)
2. Run a bitnami-docker-kubectl container
3. Run any kubectl command, such as `kubectl get pods -v=6`

**Describe the results you received:**

The request takes a while and logs a warning that kubectl is throttling itself. The verbosity allows us to see the reason for the issue is the inability to create the /.kube folder:

```
I1130 00:28:49.733712      27 cached_discovery.go:87] failed to write cache to /.kube/cache/discovery/10.20.0.1_443/autoscaling/v1/serverresources.json due to mkdir /.kube: permission denied
```

**Describe the results you expected:**

No throttling, only one request is sent. As a workaround, you can pass --cache-dir=/tmp/.kube, which results in the desired result:
```
$ kubectl --cache-dir=/tmp/.kube get pod -v=6
I1130 00:30:15.637403      42 merged_client_builder.go:163] Using in-cluster namespace
I1130 00:30:15.637628      42 merged_client_builder.go:121] Using in-cluster configuration
I1130 00:30:15.720633      42 merged_client_builder.go:121] Using in-cluster configuration
I1130 00:30:15.827677      42 merged_client_builder.go:121] Using in-cluster configuration
I1130 00:30:15.941405      42 round_trippers.go:454] GET https://10.20.0.1:443/api/v1/namespaces/machaffe/pods?limit=500 200 OK in 24 milliseconds
NAME                     READY   STATUS    RESTARTS   AGE
debug-5ff988d744-h8wlm   1/1     Running   1          3h6m
```

A possible fix could involve just creating the /.kube folder with relaxed permissions at build-time. I don't think you can change the default cache dir aside from the --cache-dir flag.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
n/a

- Output of `docker info`:
n/a

- Output of `docker-compose version` (if applicable):
n/a

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Kubernetes with kubespray and a bunch of addons. Gatekeeper requires one CRD per policy, so that's the biggest source of CRDs.

**Comment by sylvia-a2s** [comment]
run lens as an administrator fixes this problem.
