### ISSUE TITLE
Add git to docker image

### ISSUE THREAD

**Issue by Chick3nFingDing** [bitnami/bitnami-docker-kubectl#38]
### Name and Version

bitnami/kubectl:latest

### What is the problem this feature will solve?

Adding git to the existing image will allow git clones to pull from other repos.

### What is the feature you are proposing to solve the problem?

Include git in the packages install.

**Comment by javsalgar** [comment]
Hi,

Thank you for the request! Could you elaborate the use case where kubectl requires `git` for performing Kubernetes operations?
