### ISSUE TITLE
Setting container kubeconfig directory

### ISSUE THREAD

**Issue by viniciuseduardo** [bitnami/bitnami-docker-kubectl#4]
How to map the kubernetes configuration file via volume or secrets?

Example:
`docker run --rm --name kubectl -v ~/.kube:/root/.kube bitnami/kubectl:latest version`

**Comment by miguelaeh** [comment]
Hi @viniciuseduardo ,
You can mount your `kubeconfig` file into the container and use the `--kubeconfig` flag with `kubectl`. 
For example:
```
$ docker run --rm -v /home/user/.kube/config:/bitnami/kubeconfig bitnami/kubectl --kubeconfig=/bitnami/kubeconfig get pods
```
Be sure you set the proper permissions to the file before mounting it.

**Comment by viniciuseduardo** [comment]
Thanks @miguelaeh

**Comment by miguelaeh** [comment]
I'm glad it solves your problem!!!

**Comment by melbin-francis** [comment]
How did you find the path of the config file as I assume this is the path of the config file "/home/user/", is this the default path

**Comment by migruiz4** [comment]
Hi @User0394934,

I'm sorry I'm not sure I fully understand your question. But I will try to shed some light over the command that solved this question.

```
$ docker run --rm -v /home/user/.kube/config:/bitnami/kubeconfig bitnami/kubectl --kubeconfig=/bitnami/kubeconfig get pods
```

The option `-v <host_path>:<container_path>` mounts the kubeconfig file as a volume from your Docker Host in the container. The config file is usually located at `~/.kube/config` in your host, but you could also create a new config file and load it into the container.

Then, run the kubectl container with the extra flag `--kubeconfig=<container_path>`  to use your mounted configuration.

**Comment by User0394934** [comment]
Thanks for clarifying.
