### ISSUE TITLE
Include jq command

### ISSUE THREAD

**Issue by L3o-pold** [bitnami/bitnami-docker-kubectl#9]
It could be nice to add `jq` command to run complex `kubectl` commands.

**Comment by juan131** [comment]
Hi @L3o-pold 

What about using the  `-o jsonpath='{...}'` flag? I mean, **kubectl** already supports native ways to play with the output so you can select the specific field you're interesting on.

**Comment by L3o-pold** [comment]
Hi, @juan131 

You are totally correct!

**Comment by devthejo** [comment]
jsonpath syntax supported by kubectl is not as powerfull as native one, that why we need jq, see:
https://github.com/kubernetes/kubernetes/issues/20352

**Comment by juan131** [comment]
I agree that `jsonpath` is not as powerful and flexible as `jq` @devthejo

That said, we should keep this container as slim and simple as possible IMHO. Even though it can be a little more complex to filter your results, I think it's worth in order to keep it simple.

**Comment by devthejo** [comment]
@juan131 `jsonpath` is powerful but kubectl doesn't implement the full `jsonpath` spec, it's the problem described in https://github.com/kubernetes/kubernetes/issues/20352

**Comment by juan131** [comment]
@devthejo I discussed it with the team, and we consider it actually makes sense to add it since it's sth very useful and widely extended. Also, it's officially recommended in K8s docs when regular expressions are required, see:

- https://kubernetes.io/docs/reference/kubectl/jsonpath/

We'll work on a new image revision that will includes this feature. I'll keep you updated about our progress.

**Comment by juan131** [comment]
Hi @devthejo 

I just want to let you know that new revisions of the containers were released including `jq`, see the commits below:

- branch 1.16: https://github.com/bitnami/bitnami-docker-kubectl/commit/977b8d195ac6c07707c9d0bf68b0f821bd9cbabc
- branch 1.17:  https://github.com/bitnami/bitnami-docker-kubectl/commit/214fadc48276cbb70cbf24ab4822312508ae0fe3
- branch 1.18:  https://github.com/bitnami/bitnami-docker-kubectl/commit/b2bc153a5ff500b1ef5a0617bbe1123cfd91b36b
- branch 1.19:  https://github.com/bitnami/bitnami-docker-kubectl/commit/556602a4aa0cb72fb7a5640d51c7f91a6b80bc1b
- branch 1.20: https://github.com/bitnami/bitnami-docker-kubectl/commit/fe5a6563b2021c437235a62b57258657d55910bf

**Comment by devthejo** [comment]
Hi @juan131 
Many thanks for that and the other useful tools you are providing ;)
Big up for that great reactivity !

**Comment by juan131** [comment]
You're welcome! Thank you for the great feedback.
